name: generator

on:
  push:
    branches: [master]

  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Update readme for Data Privacy
        uses: linuxsuren/yaml-readme@v0.0.13
        env:
          GH_TOKEN: ${{ secrets.GH_SECRETS }}
        with:
          pattern: 'data/*.yaml'
          output: README.md
          template: README.tpl
          username: linuxsuren
          org: linuxsuren
          repo: open-source-podcasts
